version: '2.2'

services:
  webservice:
    image: "splitsoftware/callhome:1.2"
    environment:
      - EXT_API_KEY=${SPLITIO_EXT_API_KEY}
      - API_KEY=${SPLITIO_API_KEY}
      - SPLITIO_DEBUG=${SPLITIO_DEBUG} 
    ports:
      - "${SPLITIO_SERVER_PORT:-7548}:7548"
